enum direction { TURN_LEFT_GRADUAL = 0, STRAIGHT_AHEAD = 1, TURN_RIGHT_GRADUAL = 2, TURN_LEFT_HARD = 3, TURN_RIGHT_HARD = 4 };
enum vehicleStati {STATIONARY = 0, MOVING = 1, ENCOUNTERED_OBSTACLE = 2};
